# Generated by Django 2.1.7 on 2019-03-23 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name', max_length=60)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_students', models.ManyToManyField(help_text='Assign students to assignmnet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(help_text='Enter a short description', max_length=60)),
                ('long_description', models.TextField(help_text='Enter a detailed description')),
                ('Assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name', max_length=60)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Project')),
            ],
        ),
    ]
