# Generated by Django 2.1.7 on 2019-03-29 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_take'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='take',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='take',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Enter course title', max_length=80),
        ),
        migrations.AddField(
            model_name='instruct',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Course'),
        ),
        migrations.AddField(
            model_name='instruct',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
