# Generated by Django 2.1.7 on 2019-03-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190328_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name1',
            field=models.CharField(default='SOME STRING', help_text='Enter course title', max_length=80),
        ),
    ]
