# Generated by Django 2.2 on 2019-04-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190328_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='course', help_text='Enter course title', max_length=80),
        ),
    ]
