# Generated by Django 2.2 on 2019-04-30 23:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import submission_grader.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission_grader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='files',
            field=models.FileField(max_length=255, null=True, upload_to=submission_grader.models.get_files_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'java'])]),
        ),
    ]
