# Generated by Django 2.2 on 2019-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='files',
            field=models.FileField(help_text='Submit', null=True, upload_to=''),
        ),
    ]
