# Docker Compose file for launching Django connected to a MySQL server
# running in a separate container. The Docker images are described in
# the docker/ folder below here and the database data is stored in
# db/, the Django application stored starting here.
version: "2"

networks:
  # Construct a private network for the Django server and
  # database server to communicate on
  infrastructure:
    external: false


services:
  django:
    restart: always
    build: ./docker/django/
    volumes:
      - $PWD:/usr/src/app
    ports:
      - $DJANGO_PORT:8000
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    container_name: "django_${HOST_USER_ID}_${HOST_GROUP_ID}"
    networks:
      # Join the infrastructure network
      - infrastructure
    depends_on:
      - db

  db:
    build: ./docker/mysql/
    volumes:
      - $PWD/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=django
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
      - MYSQL_DATABASE=djangodocker_db
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    container_name: "mysql_${HOST_USER_ID}_${HOST_GROUP_ID}"
    networks:
      # Add the db server to the infrastructure network
      - infrastructure
