# Generated by Django 2.2 on 2019-04-25 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_choice', models.CharField(choices=[('Student', 'STUDENT'), ('Instructor', 'INSTRUCTOR'), ('Grader', 'GRADER')], default=('Student', 'STUDENT'), max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Course')),
                ('invite_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_receiver', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('invite_sender', models.ForeignKey(default='autograderinstructor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invite_sender', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
