# Generated by Django 2.1.7 on 2019-04-15 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_auto_20190408_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Course')),
                ('invite_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_receiver', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('invite_sender', models.ForeignKey(limit_choices_to={'group_name': 'Instructor'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invite_sender', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
