# Generated by Django 2.1.7 on 2019-04-15 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_sender',
            field=models.ForeignKey(choices=[('grader', 'GRADER'), ('instructor', 'INSTRUCTOR')], on_delete=django.db.models.deletion.DO_NOTHING, related_name='invite_sender', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
