# Generated by Django 2.1.7 on 2019-04-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190415_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='group_choice',
            field=models.CharField(blank=True, choices=[('grader', 'GRADER'), ('instructor', 'INSTRUCTOR')], max_length=20),
        ),
    ]
