# Generated by Django 2.1.7 on 2019-04-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invite_group_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='group_choice',
            field=models.CharField(choices=[('grader', 'GRADER'), ('instructor', 'INSTRUCTOR'), ('student', 'STUDENT')], default=('student', 'STUDENT'), max_length=20),
        ),
    ]
