# Generated by Django 2.1.7 on 2019-04-17 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190415_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_receiver', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_sender',
            field=models.ForeignKey(default='autograderinstructor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invite_sender', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
