# Generated by Django 2.1.7 on 2019-04-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190416_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='group_choice',
            field=models.CharField(choices=[('Grader', 'GRADER'), ('Instructor', 'INSTRUCTOR'), ('Student', 'STUDENT')], default=('Student', 'STUDENT'), max_length=20),
        ),
    ]
