# Generated by Django 2.1.7 on 2019-04-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190418_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='group_choice',
            field=models.CharField(choices=[('Student', 'STUDENT'), ('Instructor', 'INSTRUCTOR'), ('Grader', 'GRADER')], default=('Student', 'STUDENT'), max_length=20),
        ),
    ]
